name = "saturdai"
main = ".open-next/worker.js"
compatibility_date = "2024-11-01"
compatibility_flags = ["nodejs_compat", "global_fetch_strictly_public"]

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

[[routes]]
pattern = "saturdai.com/*"
zone_name = "saturdai.com"

[[routes]]
pattern = "www.saturdai.com/*"
zone_name = "saturdai.com"

[[d1_databases]]
binding = "DB"
database_name = "saturdai"
database_id = "e704c1cb-3b3d-445b-ae88-b5bbdc2f6fe2"
